[opener]
edit = [
    { run = 'micro "$@"', block = true, for = "unix" }
]
image = [
    { run = 'imv "$(dirname "$1")"', block = true, desc = "imv" }
]
view_csv = [
    { run = 'csvlens "$@"', block = true, desc = "View CSV" }
]

[preview]
image_filter = "triangle"
image_quality = 75
# Yazi will automatically use Chafa for Sixel if available


[[open.prepend_rules]]
mime = "image/*"
use = "image"

[[open.prepend_rules]]
name = "*.csv"
use = "view_csv"

[[open.prepend_rules]]
mime = "text/html"
use = "open"  # "open" is Yazi's built-in command for the system default (Chrome, etc.)

[[open.prepend_rules]]
mime = "text/*"
use = "edit"
